adapt-security/adapt-authoring-ui

- app/modules/userManagement/models/userModel.js
- app/modules/userManagement/views/userView.js
Fix for adapt-security/adapt-authoring-ui/issues/4
> Add user role assign and unassign routes

- app/modules/userManagement/helpers.js
- app/modules/userManagement/views/userView.js
> Fix helper function check for current user, fixes #186

- app/libraries/polyglot.min.js
Fixes (#209)
Fix: polyglot.min.js updated to v2.4.2
> Fix: polyglot.min.js updated to v2.4.2

- app/modules/editor/themeEditor/views/editorThemingView.js
Fixes (#207) 
Fix: themes being pulled through on showPresetEdit.
> Fix: themes being pulled through on showPresetEdit.

- app/modules/editor/themeEditor/views/editorThemingView.js
Fixes (#213)
Fix: listen to destroy event to update preset dropdown.
> Fix: listen to destroy event to update preset dropdown.

- app/modules/scaffold/templates/field.hbs
Fixes (#70)
* Prevent enter key default behaviour on form fields (fixes #70)
> Fix: Prevent enter key default behaviour on form fields. (#70)

- app/libraries/selectize/js/selectize.js
- app/modules/scaffold/views/scaffoldTagsView.js
Fixes (#168)
* Typing a new tag will no longer remove existing (fixes #168)
* PostRender create tag fix (fixes #227)
* Page refresh needed before new tag is visible in the dropdown (#226)
* Selectize library updated (fixes #229)
> Fix: Tags not deleting when typing and new tags created (#168 #227 #229)

- app/modules/assetManagement/less/asset.less
- app/modules/assetManagement/templates/assetManagementListItem.hbs
- app/modules/editor/contentObject/views/editorPageArticleView.js
- app/modules/editor/contentObject/views/editorPageBlockView.js
- app/modules/editor/contentObject/views/editorPageComponentPasteZoneView.js
- app/modules/editor/contentObject/views/editorPageComponentView.js
- app/modules/editor/global/views/editorPasteZoneView.js
#239 
* page drag and drop behaviour
> Fix: page drag and drop behaviour (fixes #239)

- app/modules/projects/views/projectsSidebarView.js
- app/modules/projects/views/projectsView.js
#103 
* Added housekeeping code and fixed duplicate search results (exacerbated by typing quickly)
> Fix: duplicate search results (fixes #103)

- app/modules/scaffold/views/scaffoldTagsView.js
#249 
* Use getValue to check selected items, force focus to avoid cursor vanishing. #249
> Fix: use getValue to check selected items, force focus to avoid cursor vanishing. (fixes #249)

- app/modules/assetManagement/views/assetManagementEditAssetView.js
- app/modules/scaffold/views/scaffoldTagsView.js
Fixes https://github.com/adapt-security/adapt-authoring-ui/issues/241 
Fixes https://github.com/adapt-security/adapt-authoring-ui/issues/142
* fix functionality to add and remove all tags from assets (fixes #241 & #142)
> Fix: fix functionality to add and remove all tags from assets (fixes #241 & #142)

- app/modules/editor/course/views/editorCourseEditView.js
Fixes #257
* Fixes error shown on course creation
> Fix: Error on course creation (fixes #257)

- app/modules/assetManagement/views/assetManagementEditAssetView.js
#259
* New asset creation with no tags
> Fix: New asset creation when no tags set (fixes #259)

- app/modules/editor/contentObject/views/editorPageView.js
#271 
* Update editorPageView render to try/catch consistent with editorDataLoader (#271)
[//]: # (Mention any other dependencies)
> Fix: update editorPageView render to try/catch consistent with editorDataLoader (fixes #271)

- app/modules/editor/contentObject/views/editorPageView.js
#277 
* apiCollection fetch call removed on pageEditor render (fixes #277)
> Fix: apiCollection fetch call removed on pageEditor render (fixes #277)

- app/modules/pluginManagement/views/pluginManagementView.js
#279 
* remove .length from checking collection in renderPluginTypeViews (fixes #279)
> Fix: remove .length from checking collection in renderPluginTypeViews (fixes #279)

- app/modules/notify/plugins/snackbar/index.js
#281 
* Optional chaining added to data on snackbar close (fixes #281)
> Fix: Optional chaining added to data on snackbar close (fixes #281)

- app/modules/projects/views/projectsView.js
#293 
* prevent projects being duplicated in dashboard
> Fix: prevent projects being duplicated in dashboard (fixes #293)

- app/modules/scaffold/views/scaffoldListView.js
#305 
* return early for removeItem amended (fixes #305)
> Fix: return early for removeItem amended (fixes #305)

- app/modules/editor/global/views/editorView.js
#308 
* Added loading popup when copying page/menu
> Update: added loading popup when copying page/menu (fixes #308)

- app/modules/editor/global/editorDataLoader.js
#274 
* prevent Origin.editor.data.content from being overwritten until fetch completed (fixes #274)
> Fix: prevent Origin.editor.data.content from being overwritten until fetch completed (fixes #274)

- app/modules/editor/global/editorDataLoader.js
#326 
* scope check for new data to selected course
> Fix: scope check for new data to selected course (fixes #326)

- app/modules/assetManagement/views/assetManagementCollectionView.js
#330 
* assetManagementCollectionView this.pageSize calculations fixed (fixes #330)
> Fix: assetManagementCollectionView this.pageSize calculations fixed (fixes #330)

- app/modules/projects/views/projectsView.js
#332 
* projectsView this.pageSize calculations fixed (fixes #332)
> Fix: projectsView this.pageSize calculations fixed (fixes #332)
